language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.15
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.18
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.18
          sudo: required
          dist: trusty
          group: edge
          env: HHVMPHP7=1
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
        - env: HHVMPHP7=1

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction
before_script:
  - if [[ "$HHVMPHP7" ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
script: scripts/travis
after_script: scripts/travis-after

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.1
        - secure: "wtPRNm+x987/5CBkbz/hsJLvglEtGE4v1SpMA5Aun4f39ohhYNTPMNsSeg5KcPLWNIhx+9K/UYGACfp1+kPHiIAT5xdJojbhA82s87vCzfyGYJSKE2bt+nRujxRson3mdAbtRp0PHKiXG+x96qKyNgpTQeZiEfRXcsEz78ynAjdmGM5Y8uNC9lCypVZBZGXRqBjvakNta1o3XJ58oHIo4sHnWpxPG6jMtsojzbJKE6O8tGHV41fTHrYo+MqAY0hz86JpwYEjp/+0bOq/6pRzM0virXAxu29dunidkd5zls9ezoZpj1UTN9wOi4kuT6SODFPQteQ5RUcprruvANPxmOyl3nt9yHVb5TxbESWVGmIrMsiq0LiEEhIhZAHifo7+V0+HCgi/S1UN7eiJiTNctStYQ3wNAR5S0VCyvtoqtaNLhJjZ1CZrnP2DDJCtElcuHbrzO05UZbZyR7gPTJ4sd4ZELJ2dYOJNAYe9PGPREcVDy8H3XElG3wYXYCebVo5VDQ6YLTD/qdN+MyVgislHeQRqKO4yE8invsRKZoXpz/lNaQmTDRQJBgF7F0AE42z5JOw/om+goBMmrpWo9WPR5o3kv6nPe+kwwCpTxIPI08LEdRsFLK1JjCGU6IoDWgHDUSC+sY3QrYZaHtfudh53AahP2fVmQ8RYXDk0pAahkt8="

cache:
    directories:
        - $HOME/.composer

sudo: false
