language: php

matrix:
    include:
        - php: 5.4
          dist: trusty
        - php: 5.5
          dist: trusty
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: nightly
        - php: hhvm-3.18
          sudo: required
          services:
              - docker
          env: HHVM=1
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction
script: scripts/travis
after_script: scripts/travis-after

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.1
        - secure: "rABto8EK2n8oPqwXNUVYL5tfZcT3UptBmQ5TxGr3DoVDfUpSFAi9gsDouAa7ybuB138KzUwclHD0bujyBgWVg7Axnv2YKha42IHhM/bPAujFZdLOd7wVaAuOi9WgPFKzqxbMYjDk6NRDVpSSOH0jisCoV8er65ez0YTI2v4ZSWIEfnA4DM1YOR4Y+78hCPV4OhF62VIDhcTh7GEljUxjjV2wvTDTh9RK0Rigs8ocGBl3SJZ6OLAGN+cwuo8+cKBNJwLMhq4B58UmnZtw4UHKgB58U97Whjv15f9ghgAa1gilxWxGNqK/QFzGBSv0m4w7AVnBqi0xWCSsQNr8pleDEWgafWVHn94skzhVUDp2oFl1eZ3E23VykNRZpBLyumHmxpozB0LtZs1hvPEDBOtefkggf0ykTvQ7ThByEDwMzCd6DFrBD+phHWW9Et8hMadmzyYLbEEondU5JyVpwiaiEnm7jbXNgxL0C/kiVbarbN7e9GWtaiMPC8DbCS+cMBVb191foO6ZQEL+RTVBbVuOhPt9omTJjCMa5hW92DHMhFYEz7QqrYppMzidr9IZAeUMpLbO5W19LoU7IIa5VHV3s7z4Rvumy7RoQ9j5tMxjCvLMAryTDb2xnpxuTDNrZqHeH8/Vui9QcTpdWdtA5z6akjl9GbFpGJ8UxGiyIOQzuDE="

cache:
    directories:
        - $HOME/.composer

sudo: false
